import type { Question } from "../game/types";

const ZOMBIE_GAIN = { easy: 2, medium: 3, hard: 5 } as const;

export const questions: Question[] = [
  // ── C# ──────────────────────────────────────────────
  {
    id: 1,
    language: "csharp",
    difficulty: "easy",
    incidentTitle: "THE FIRST COMMIT",
    question: "What is the value of x after this code runs?",
    code: `int x = 5;\nx = x + 3;\nConsole.WriteLine(x);`,
    answers: ["5", "8", "3", "Error"],
    correctAnswer: 1,
    explanation: "x starts at 5, then 3 is added, resulting in 8.",
    zombieGain: ZOMBIE_GAIN.easy,
  },
  {
    id: 2,
    language: "csharp",
    difficulty: "easy",
    incidentTitle: "THE NULL POINTER",
    question: "What will this print?",
    code: `int a = 7;\nint b = 2;\nConsole.WriteLine(a / b);`,
    answers: ["3.5", "3", "4", "Error"],
    correctAnswer: 1,
    explanation: "Integer division in C# truncates the decimal part, so 7 / 2 equals 3.",
    zombieGain: ZOMBIE_GAIN.easy,
  },
  {
    id: 3,
    language: "csharp",
    difficulty: "easy",
    incidentTitle: "WHO DEPLOYED THIS?",
    question: "What is the output?",
    code: `string name = "Dev";\nstring greeting = "Hello, " + name + "!";\nConsole.WriteLine(greeting);`,
    answers: ["Hello, Dev!", "Hello, name!", "Hello, +name+!", "Error"],
    correctAnswer: 0,
    explanation: "The + operator concatenates strings, inserting the value of name.",
    zombieGain: ZOMBIE_GAIN.easy,
  },
  {
    id: 4,
    language: "csharp",
    difficulty: "easy",
    incidentTitle: "THE LOOP THAT NEVER ENDED",
    question: "What does this print?",
    code: `bool isOpen = false;\nif (isOpen) {\n    Console.WriteLine("Open");\n} else {\n    Console.WriteLine("Closed");\n}`,
    answers: ["Open", "Closed", "true", "false"],
    correctAnswer: 1,
    explanation: "isOpen is false, so the else branch runs and prints 'Closed'.",
    zombieGain: ZOMBIE_GAIN.easy,
  },
  {
    id: 5,
    language: "csharp",
    difficulty: "medium",
    incidentTitle: "COFFEE.exe HAS STOPPED RESPONDING",
    question: "How many times does 'Tick' get printed?",
    code: `for (int i = 0; i < 5; i++) {\n    Console.WriteLine("Tick");\n}`,
    answers: ["4", "5", "6", "Infinite"],
    correctAnswer: 1,
    explanation: "The loop runs for i = 0 through 4, which is 5 iterations.",
    zombieGain: ZOMBIE_GAIN.medium,
  },
  {
    id: 6,
    language: "csharp",
    difficulty: "medium",
    incidentTitle: "PRODUCTION IS ON FIRE",
    question: "What is printed?",
    code: `int[] nums = { 10, 20, 30 };\nConsole.WriteLine(nums[2]);`,
    answers: ["10", "20", "30", "Error: index out of range"],
    correctAnswer: 2,
    explanation: "Arrays are zero-indexed, so nums[2] is the third element, 30.",
    zombieGain: ZOMBIE_GAIN.medium,
  },
  {
    id: 7,
    language: "csharp",
    difficulty: "medium",
    incidentTitle: "THE DEAD ARRAY",
    question: "What does Square(4) return?",
    code: `int Square(int n) {\n    return n * n;\n}`,
    answers: ["8", "16", "4", "Error"],
    correctAnswer: 1,
    explanation: "Square multiplies n by itself: 4 * 4 = 16.",
    zombieGain: ZOMBIE_GAIN.medium,
  },
  {
    id: 8,
    language: "csharp",
    difficulty: "hard",
    incidentTitle: "WHO TOUCHED MAIN?",
    question: "What is Count after this code runs?",
    code: `List<string> tickets = new List<string>();\ntickets.Add("BUG-1");\ntickets.Add("BUG-2");\ntickets.Remove("BUG-1");\nConsole.WriteLine(tickets.Count);`,
    answers: ["0", "1", "2", "Error"],
    correctAnswer: 1,
    explanation: "Two tickets were added and one was removed, leaving a Count of 1.",
    zombieGain: ZOMBIE_GAIN.hard,
  },
  {
    id: 9,
    language: "csharp",
    difficulty: "hard",
    incidentTitle: "THE MERGE CONFLICT",
    question: "What does this print?",
    code: `class Zombie {\n    public int Health = 100;\n    public void Bite() {\n        Health -= 10;\n    }\n}\n\nZombie z = new Zombie();\nz.Bite();\nz.Bite();\nConsole.WriteLine(z.Health);`,
    answers: ["100", "90", "80", "Error"],
    correctAnswer: 2,
    explanation: "Bite() is called twice, reducing Health by 10 each time: 100 - 10 - 10 = 80.",
    zombieGain: ZOMBIE_GAIN.hard,
  },
  {
    id: 10,
    language: "csharp",
    difficulty: "hard",
    incidentTitle: "MARTIN FROM BACKEND",
    question: "What does this print?",
    code: `List<int> scores = new List<int> { 1, 2, 3, 4, 5 };\nint total = scores.Where(s => s % 2 == 0).Sum();\nConsole.WriteLine(total);`,
    answers: ["6", "9", "15", "Error"],
    correctAnswer: 0,
    explanation: "Where filters even numbers (2 and 4), and Sum adds them: 2 + 4 = 6.",
    zombieGain: ZOMBIE_GAIN.hard,
  },

  // ── JavaScript ──────────────────────────────────────
  {
    id: 11,
    language: "javascript",
    difficulty: "easy",
    incidentTitle: "THE STACK OVERFLOW",
    question: "What happens when this code runs?",
    code: `const level = 1;\nlevel = 2;\nconsole.log(level);`,
    answers: ["1", "2", "undefined", "TypeError: Assignment to constant variable."],
    correctAnswer: 3,
    explanation: "const variables cannot be reassigned, so this throws a TypeError.",
    zombieGain: ZOMBIE_GAIN.easy,
  },
  {
    id: 12,
    language: "javascript",
    difficulty: "easy",
    incidentTitle: "UNDEFINED IS NOT A FUNCTION",
    question: "What is printed?",
    code: `const bugs = ["null ref", "off-by-one"];\nbugs.push("memory leak");\nconsole.log(bugs.length);`,
    answers: ["2", "3", "4", "Error"],
    correctAnswer: 1,
    explanation: "push() adds one item to the array, making its length 3.",
    zombieGain: ZOMBIE_GAIN.easy,
  },
  {
    id: 13,
    language: "javascript",
    difficulty: "easy",
    incidentTitle: "THE ZOMBIE PROCESS",
    question: "What does this print?",
    code: `console.log(0 == "0");\nconsole.log(0 === "0");`,
    answers: ["true, true", "false, false", "true, false", "false, true"],
    correctAnswer: 2,
    explanation:
      '== performs type coercion (0 equals "0"), while === checks type and value, so it is false.',
    zombieGain: ZOMBIE_GAIN.easy,
  },
  {
    id: 14,
    language: "javascript",
    difficulty: "medium",
    incidentTitle: "THE INFINITE RECURSION",
    question: "What is printed?",
    code: `const dev = { name: "Alex", role: "backend" };\ndev.role = "zombie";\nconsole.log(dev.role);`,
    answers: ["backend", "zombie", "undefined", "Error"],
    correctAnswer: 1,
    explanation: "Object properties can be reassigned; role is updated to 'zombie'.",
    zombieGain: ZOMBIE_GAIN.medium,
  },
  {
    id: 15,
    language: "javascript",
    difficulty: "medium",
    incidentTitle: "SEGMENTATION FAULT (CORE DUMPED)",
    question: "What does this print?",
    code: `function greet(name) {\n    return "Hi " + name;\n}\nconsole.log(greet());`,
    answers: ["Hi ", "Hi undefined", "Error", "Hi null"],
    correctAnswer: 1,
    explanation:
      "No argument is passed, so name is undefined, and it gets concatenated as the string 'undefined'.",
    zombieGain: ZOMBIE_GAIN.medium,
  },
  {
    id: 16,
    language: "javascript",
    difficulty: "medium",
    incidentTitle: "THE GHOST IN THE REPO",
    question: "What is printed?",
    code: `const double = x => x * 2;\nconsole.log(double(6));`,
    answers: ["6", "12", "62", "Error"],
    correctAnswer: 1,
    explanation: "The arrow function doubles its argument: 6 * 2 = 12.",
    zombieGain: ZOMBIE_GAIN.medium,
  },
  {
    id: 17,
    language: "javascript",
    difficulty: "medium",
    incidentTitle: "IT WORKED YESTERDAY",
    question: "What is printed?",
    code: `const nums = [1, 2, 3];\nconst doubled = nums.map(n => n * 2);\nconsole.log(doubled);`,
    answers: ["[1, 2, 3]", "[2, 4, 6]", "[1, 4, 9]", "undefined"],
    correctAnswer: 1,
    explanation: "map() returns a new array with each element doubled.",
    zombieGain: ZOMBIE_GAIN.medium,
  },
  {
    id: 18,
    language: "javascript",
    difficulty: "hard",
    incidentTitle: "THE SILENT EXCEPTION",
    question: "What is printed?",
    code: `const incidents = [5, 12, 8, 3, 20];\nconst critical = incidents.filter(n => n > 10);\nconsole.log(critical);`,
    answers: ["[12, 20]", "[5, 8, 3]", "[5, 12, 8, 3, 20]", "[]"],
    correctAnswer: 0,
    explanation: "filter() keeps only elements greater than 10: 12 and 20.",
    zombieGain: ZOMBIE_GAIN.hard,
  },
  {
    id: 19,
    language: "javascript",
    difficulty: "hard",
    incidentTitle: "THE OFF-BY-ONE",
    question: "What is printed?",
    code: `const hours = [8, 10, 12];\nconst total = hours.reduce((sum, h) => sum + h, 0);\nconsole.log(total);`,
    answers: ["0", "8", "10", "30"],
    correctAnswer: 3,
    explanation: "reduce() accumulates the sum starting at 0: 8 + 10 + 12 = 30.",
    zombieGain: ZOMBIE_GAIN.hard,
  },
  {
    id: 20,
    language: "javascript",
    difficulty: "hard",
    incidentTitle: "THE HAUNTED LEGACY CODE",
    question: "What is logged last?",
    code: `console.log("A");\nsetTimeout(() => console.log("B"), 0);\nconsole.log("C");`,
    answers: ["A, B, C", "A, C, B", "B, A, C", "C, B, A"],
    correctAnswer: 1,
    explanation:
      "setTimeout schedules its callback after the current synchronous code finishes, so B logs last even with a 0ms delay.",
    zombieGain: ZOMBIE_GAIN.hard,
  },

  // ── Python ──────────────────────────────────────────
  {
    id: 21,
    language: "python",
    difficulty: "easy",
    incidentTitle: "RACE CONDITION AT MIDNIGHT",
    question: "What is printed?",
    code: `level = 1\nlevel = level + 1\nprint(level)`,
    answers: ["1", "2", "3", "Error"],
    correctAnswer: 1,
    explanation: "level starts at 1 and is incremented by 1, resulting in 2.",
    zombieGain: ZOMBIE_GAIN.easy,
  },
  {
    id: 22,
    language: "python",
    difficulty: "easy",
    incidentTitle: "THE MEMORY LEAK",
    question: "What is printed?",
    code: `tasks = ["deploy", "test"]\ntasks.append("debug")\nprint(len(tasks))`,
    answers: ["2", "3", "4", "Error"],
    correctAnswer: 1,
    explanation: "append() adds one item, making the list length 3.",
    zombieGain: ZOMBIE_GAIN.easy,
  },
  {
    id: 23,
    language: "python",
    difficulty: "easy",
    incidentTitle: "THE ROLLBACK THAT WASN'T",
    question: "What is printed?",
    code: `dev = {"name": "Sam", "status": "tired"}\nprint(dev["status"])`,
    answers: ["name", "Sam", "status", "tired"],
    correctAnswer: 3,
    explanation: 'Indexing a dictionary with a key returns its value; dev["status"] is \'tired\'.',
    zombieGain: ZOMBIE_GAIN.easy,
  },
  {
    id: 24,
    language: "python",
    difficulty: "medium",
    incidentTitle: "WHO WROTE THIS COMMENT?",
    question: "What is printed?",
    code: `total = 0\nfor i in range(4):\n    total += i\nprint(total)`,
    answers: ["4", "6", "10", "0"],
    correctAnswer: 1,
    explanation: "range(4) yields 0, 1, 2, 3; their sum is 0+1+2+3 = 6.",
    zombieGain: ZOMBIE_GAIN.medium,
  },
  {
    id: 25,
    language: "python",
    difficulty: "medium",
    incidentTitle: "THE DEPRECATED WARNING",
    question: "What is printed?",
    code: `def add(a, b=10):\n    return a + b\n\nprint(add(5))`,
    answers: ["5", "10", "15", "Error"],
    correctAnswer: 2,
    explanation: "b defaults to 10 when not provided, so add(5) returns 5 + 10 = 15.",
    zombieGain: ZOMBIE_GAIN.medium,
  },
  {
    id: 26,
    language: "python",
    difficulty: "medium",
    incidentTitle: "THE HOTFIX HORROR",
    question: "What is printed?",
    code: `value = None\nprint(value == None)\nprint(value is None)`,
    answers: ["True, True", "False, False", "True, False", "False, True"],
    correctAnswer: 0,
    explanation: "Both == and is correctly identify None here, so both print True.",
    zombieGain: ZOMBIE_GAIN.medium,
  },
  {
    id: 27,
    language: "python",
    difficulty: "hard",
    incidentTitle: "THE FROZEN DEPLOY PIPELINE",
    question: "What is printed?",
    code: `logs = ["a", "b", "c", "d", "e"]\nprint(logs[1:4])`,
    answers: ["['a', 'b', 'c']", "['b', 'c', 'd']", "['b', 'c', 'd', 'e']", "['a', 'b', 'c', 'd']"],
    correctAnswer: 1,
    explanation: "Slicing [1:4] returns elements at indices 1, 2, 3: 'b', 'c', 'd'.",
    zombieGain: ZOMBIE_GAIN.hard,
  },
  {
    id: 28,
    language: "python",
    difficulty: "hard",
    incidentTitle: "THE UNTESTED BRANCH",
    question: "What is printed?",
    code: `nums = [1, 2, 3, 4, 5]\nresult = [n * n for n in nums if n % 2 == 0]\nprint(result)`,
    answers: ["[1, 4, 9, 16, 25]", "[4, 16]", "[2, 4]", "[]"],
    correctAnswer: 1,
    explanation: "The comprehension squares only the even numbers (2 and 4), giving [4, 16].",
    zombieGain: ZOMBIE_GAIN.hard,
  },
  {
    id: 29,
    language: "python",
    difficulty: "hard",
    incidentTitle: "THE FINAL PULL REQUEST",
    question: "What is printed?",
    code: `try:\n    result = 10 / 0\nexcept ZeroDivisionError:\n    print("caught")\nelse:\n    print("no error")\nfinally:\n    print("done")`,
    answers: ["caught, done", "no error, done", "caught", "done"],
    correctAnswer: 0,
    explanation:
      "Dividing by zero raises ZeroDivisionError, so 'caught' prints, then 'done' from finally always runs.",
    zombieGain: ZOMBIE_GAIN.hard,
  },
  {
    id: 30,
    language: "python",
    difficulty: "hard",
    incidentTitle: "THE LAST STANDUP",
    question: "What is printed?",
    code: `class Zombie:\n    def __init__(self, health):\n        self.health = health\n\n    def bite(self):\n        self.health -= 20\n\nz = Zombie(100)\nz.bite()\nprint(z.health)`,
    answers: ["100", "80", "20", "Error"],
    correctAnswer: 1,
    explanation: "bite() reduces health by 20: 100 - 20 = 80.",
    zombieGain: ZOMBIE_GAIN.hard,
  },
];
